openapi: 3.0.1
info:
  title: Map Colonies API Gateway
  description: Map Colonies Applications API Gateway service, used as entry point
    to map colonies backend services
  version: 1.0.1
servers:
- url: http://swagger.local:10010/api/v1
- url: https://swagger.local:10010/api/v1
paths: {}
components: {}
x-config-validation-key: "true"
